# Build stage
FROM node:18 AS build
WORKDIR /app
COPY . .
RUN npm install && npm run build --prod

# Serve stage
FROM nginx:alpine
COPY --from=build /app/dist/my-angular-app /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

